### Initialising input and Output Matrices

In [61]:
import numpy as np

x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y=np.array([[1],[1],[0]])
lr=0.1
print("Input")
print(x)

print("Expected output")
print(y)

print("Learning rate")
print (lr)

Input
[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
Expected output
[[1]
 [1]
 [0]]
Learning rate
0.1


### Initialising random values for Weight and Biases

In [69]:
wh = np.random.random((4,3))
bh = np.random.random((1,3))
wout=np.random.random((3,1))
bout=np.random.random((1,1))

print("Weight at hidden layer")
print(wh)
print("Bias at hidden layer")
print(bh)
print("Weight at output layer")
print(wout)
print("Bias at output layer")
print(bout)

Weight at hidden layer
[[ 0.55757857  0.53705154  0.17444553]
 [ 0.1094706   0.96630393  0.50660854]
 [ 0.20286468  0.56018757  0.13061052]
 [ 0.70976841  0.77847709  0.7014725 ]]
Bias at hidden layer
[[ 0.48498012  0.81467324  0.03066518]]
Weight at output layer
[[ 0.91422133]
 [ 0.95832739]
 [ 0.34122907]]
Bias at output layer
[[ 0.99358184]]


### Calculate hidden layer input

In [32]:
hidden_layer_input = np.dot(x,wh) + bh

print("Hidden layer input")
print(hidden_layer_input)

Hidden layer input
[[ 1.73783775  2.21893273  1.97140658]
 [ 2.390764    2.2548835   2.19127344]
 [ 0.86552241  1.49335235  1.20500313]]


### Perform non-linear transformation on hidden linear input

In [38]:
def sigmoid(x,derivative=False):
    return x*(1-x) if derivative else 1/(1+np.exp(-x))
    

hiddenlayer_activations = sigmoid(hidden_layer_input)
print("Hidden layer activations")
print(hiddenlayer_activations)

Hidden layer activations
[[ 0.85041221  0.90193684  0.87776211]
 [ 0.9161203   0.90507094  0.89946312]
 [ 0.70381315  0.81658091  0.76941362]]


### Perform linear and non-linear transformation of hidden layer activation at output layer

In [39]:
output_layer_input = np.dot(hiddenlayer_activations,wout)+bout

print("Output layer input")
print(output_layer_input)


output = sigmoid(output_layer_input)
print("Output")
print(output)

Output layer input
[[ 0.93469856]
 [ 0.95233693]
 [ 0.87994471]]
Output
[[ 0.71802755]
 [ 0.72158491]
 [ 0.70681076]]


### Calculate gradient of Error(E) at output layer

In [47]:
E = y-output

print("Gradient of error")
print(E)

Gradient of error
[[ 0.28197245]
 [ 0.27841509]
 [-0.70681076]]


### Compute slope at output and hidden layer

In [51]:
Slope_output_layer= sigmoid(output,True)

print"Slope output layer"
print Slope_output_layer

Slope_hidden_layer =sigmoid(hiddenlayer_activations,True)
print "Slope hidden layer"
print Slope_hidden_layer

Slope output layer
[[ 0.20246399]
 [ 0.20090013]
 [ 0.20722931]]
Slope hidden layer
[[ 0.12721128  0.08844678  0.10729579]
 [ 0.0768439   0.08591753  0.09042921]
 [ 0.2084602   0.14977653  0.1774163 ]]


### Compute delta at output layer

In [62]:
d_output = E *Slope_output_layer*lr

print "Delta output"
print d_output

Delta output
[[ 0.00570893]
 [ 0.00559336]
 [-0.01464719]]


### Calculate Error at hidden layer

In [75]:
Error_at_hidden_layer = np.dot(d_output,wout.T)
print"Error at hidden layer"
print(Error_at_hidden_layer)

Error at hidden layer
[[ 0.00521866  0.00546803  0.00194595]
 [ 0.00511302  0.00535734  0.00190656]
 [-0.01338933 -0.01402912 -0.00499265]]


### Compute delta at hidden layer

In [74]:
d_hiddenlayer = Error_at_hidden_layer * Slope_hidden_layer
print "Delta at Hidden layer"
print(d_hiddenlayer)

Delta at Hidden layer
[[  1.34845554e-03   2.77725576e-05   1.53007450e-03]
 [  7.98066186e-04   2.64322517e-05   1.26344746e-03]
 [ -5.66935972e-03  -1.20663935e-04  -6.49117476e-03]]


### Update weight at both output and hidden layer

In [73]:
wout = wout + np.dot(hiddenlayer_activations.T,d_output)*lr
print "Update weight at output layer"
print(wout)

wh = wh+np.dot(x.T,d_hiddenlayer)*lr
print "Updated weight at hidden layer"
print(wh)

Update weight at output layer
[[ 0.9141224 ]
 [ 0.95780265]
 [ 0.34086078]]
Updated weight at hidden layer
[[ 0.55822253  0.5370678   0.17528359]
 [ 0.10776979  0.96626773  0.50466119]
 [ 0.20350863  0.56020383  0.13144858]
 [ 0.70830702  0.77844882  0.69990419]]


### Update biases at both output and hidden layer

In [83]:
bh = bh + np.sum(d_hiddenlayer,axis=0)*lr
print "Update bias at hidden layer"
print bh

bout = bout + np.sum(d_output,axis=0)*lr
print "Updated bias at output layer"
print bout

Update bias at hidden layer
[[ 0.48286642  0.81463336  0.02844659]]
Updated bias at output layer
[[ 0.9915749]]
